# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:latest

pipelines:
  branches:
    master:
      - step:
          clone:
            enabled: false
          deployment: staging
          script:
            - echo "------> Ready to deploy <------"
      - step:
          clone:
            enabled: false
          deployment: production
          trigger: manual
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: "root"
                SERVER: "103.19.88.158"
                SSH_KEY: $MY_SSH_KEY
                MODE: "command"
                PORT: "8824"
                COMMAND: "cd /www/wwwroot/referloan.in/ && ./pull.sh" # path to a script in your repository