import { useRouter } from 'next/router'
import axios from 'axios';

function sink() {

  return (
    <div></div>
  )
}


export async function getServerSideProps(context)
{
  const res1  = await axios("https://testapi.referloan.in/api/categories");

  const category = await prisma.category.upsert({
    where: {
        id_hash: {  // id_hash is the type generated by Prisma. Might be called something else though. 
            id: 1
        }
    },
    update: {
        name: "cat 1",
    },
    create: {
        name: "cat 1",
        id: 1,
    },
})
  // sink to db

  const res2  = await axios("https://testapi.referloan.in/api/products");
  
  const res3  = await axios("https://testapi.referloan.in/api/banks");

}

export default sink